# action.yml
name: "static action"
description: "runs static build against markdown and amber templates to generate a single page"
author: "stephenhu"
inputs:
  source:
    description: "source file path"
    required: true
    default: "."
runs:
  using: "docker"
  image: "docker://ghcr.io/stephenhu/static:latest"
brand:
  icon: "layers"
  color: "blue"